version: '3.7'

services:
  postgres:
    image: postgres:12.0
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - DEBUG=1
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
