version: '3.7'

services:
  postgres:
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      - DEBUG=1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - vidcuss-postgres-data:/var/lib/postgresql/data

volumes:
  vidcuss-postgres-data:
