name: CI

on: push

jobs:
  build-elixir:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:12.1
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2.3
          elixir-version: 1.9.4

      - name: Cache mix modules
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Compile
        run: mix compile --warnings-as-errors
        env:
          MIX_ENV: test

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Credo
        run: mix credo --strict
        env:
          MIX_ENV: test

      - name: Run Tests
        run: mix test

      - name: Cache PLTS tables
        uses: actions/cache@v1
        with:
          path: priv/plts
          key: ${{ runner.os }}-dialyzer

      - name: Cache dev build
        uses: actions/cache@v1
        with:
          path: _build/dev
          key: ${{ runner.os }}-build-dev

      - name: Dialyzer
        run: mix dialyzer --halt-exit-status --format short

  build-node:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12.13.0"

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Check Types
        run: yarn check-types

      - name: Check Formatting
        run: yarn check-formatting

      - name: Build
        run: yarn build

      - name: Commit Lint
        run: yarn commit-lint
